### ISSUE TITLE
let lodash as peerDependency?

### ISSUE THREAD

**Issue by naivefun** [nanoporetech/jmespath-plus#1]
It could downsize the bundle size?

**Comment by glenveegee** [comment]
What would be great is if we could build a collection of native functions so that we don't need lodash in future at all. I lazily added lodash and it turns out there are many functions that won't work in jmespath-plus due to the nature of the call signatures. I'll experiment with lodash as a peer dependency but I'd also urge anyone out there to help build a collection of jmespath(-plus) functions that makes lodash irrelevant

**Comment by naivefun** [comment]
@glenveegee Lodash is so popular that I see it on basically every project. Maybe keeping it is not a bad idea since many func would be re-implementation of lodash?

**Comment by glenveegee** [comment]
So lodash in jmespath-plus is a build time dependency so it should definitely move out of dependencies and probably into dev or peer dependencies.

We've been looking into the bundle size and it turns out the bundle is not *that* much bigger than the jmespath bundle (102 kB vs 25kB). The scariest number is the unpacked size being reported by NPM and this is derived from whatever we distribute in the `dist` folder. This contains a number of MAP files for minified and unminified (silly I know) bundles for both ESM and UMD bundles.

Keeping lodash is the easiest way to provide maximum functionality with the least amount of work :). The thing that is missing though is the type checking and argument validation that jmespath provides. The current implementation lets you run lodash functions but won't give you useful information when an argument type is wrong or the wrong number of arguments are provided. This is why native jmespath functions is definitely something we hope to expand on in future - working with the community of course.

**Comment by glenveegee** [comment]
Okay. So I've set `lodash` as a peer dependency which has shrunk the bundle from 4.8MB to 545 kB. The reason for the big drop in size is that we're no longer shipping lodash in the various jmespath-plus bundles. We were doing it in 5 different ways (CJS and UMD minified and un-minified + tsc compiled source). That's obviously now down to 0 (zero) and lodash must be picked up from the parent scope
